import { prisma } from '@/lib/prisma'
import { TimeWallTable } from '@/components/admin/AdminTables'
import { TIMEWALL_REFERENCE_PREFIX } from '@/lib/timewall'

export const dynamic = 'force-dynamic'

export default async function AdminTimeWallPage() {
  const [transactions, pendingCount] = await Promise.all([
    prisma.transaction.findMany({
      where: {
        reference: {
          startsWith: TIMEWALL_REFERENCE_PREFIX,
        },
      },
      include: {
        user: {
          select: {
            name: true,
            email: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    }),
    prisma.transaction.count({
      where: {
        status: 'PENDING',
        reference: {
          startsWith: TIMEWALL_REFERENCE_PREFIX,
        },
      },
    }),
  ])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">TimeWall Task Approvals ({pendingCount})</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Review and verify task rewards generated by users via TimeWall offerwall before they are credited to the user's Task Wallet.
        </p>
      </div>
      <div className="premium-card p-6">
        <TimeWallTable data={JSON.parse(JSON.stringify(transactions))} />
      </div>
    </div>
  )
}
